### ISSUE TITLE
Suggestions: Adding the Python code directly

### ISSUE THREAD

**Issue by vitorgalvao** [fedecalendino/alfred-world-clock#1]
The current way of sharing the workflow is atypical. It ships with a Python distribution which is ARM-only and significantly increases the size of the workflow. Plus it’s unsigned, so user’s can’t inspect the code and will get a warning from macOS that it is from an unidentified developer.

This means fewer users will have access to it or try it.

You can use `/usr/bin/python3` directly, which is a shim on macOS but will install Python 3 when first called. A macOS GUI dialog guides users through the process.

Also, note that due to not having a Title in the Script Filter, it won’t show up in the list of results as users type part of the name.

**Comment by fedecalendino** [comment]
Oh! Thanks for the comments, the ARM-only its because i've been using my M1 to generate binaries with nuitka but I wasn't aware of that limitation.

I'll try to update them over the week. Thanks again!
