### ISSUE TITLE
Time format options

### ISSUE THREAD

**Issue by ashbressler** [fedecalendino/alfred-world-clock#11]
Hi,

Would it be possible to use the computer's preferred date/time format option for the date/time display. Right now I have my computer set to use AM/PM and not 24-hour time, but the display is always in 24 hour time.

Thanks,

Allan

**Comment by fedecalendino** [comment]
Hi!

I dont know if I have a way to fetch that information from python.

I'll take a look and let you know.

Fede

**Comment by ashbressler** [comment]
Yea, I took a quick look at the code, but I couldn't figure it out very quickly. I'll look at it a bit more and see if I can figure it out as well.

**Comment by fedecalendino** [comment]
@ashbressler in the meantime I added an AM/PM format option.

Its available in `v2.1.0`: https://github.com/fedecalendino/alfred-world-clock/releases


Let me know if that works for you.
Fede.

**Comment by ashbressler** [comment]
This works for me, thanks so much for adding this feature so quickly!
