### ISSUE TITLE
Unable to see results in Alfred 5

### ISSUE THREAD

**Issue by Rynogertie** [fedecalendino/alfred-world-clock#12]
Hello @fedecalendino 

I have installed and configured alfred-world-clock per instructions, but when I launch via the keyword in Alfred 5 it briefly shows World Clock - Calculating times... at the top of the results list but then quickly disappears without producing any results. Any idea how I can fix this? 

I haven't modified anything and downloaded directly into Alfred via the Gallery.

A great workflow and I'm keen to see it in action!

Thanks

**Comment by fedecalendino** [comment]
Hi @Rynogertie , im guessing you might be missing something on your macos installation.

Would you mind sharing with me if you can see any errors on the debug screen from alfred?

https://www.alfredapp.com/help/workflows/advanced/debugger/

Cheers,
Fede.

**Comment by Rynogertie** [comment]
Thanks for quick reply @fedecalendino 

I'm seeing this:

![Screenshot 2023-02-01 at 13 47 45](https://user-images.githubusercontent.com/124165847/216060594-e61dffdf-b070-43bb-9de6-66d77e1c53f3.png)

**Comment by fedecalendino** [comment]
Ohhh xcrun, the usual suspect haha

Check this issue for a fix: https://github.com/fedecalendino/alfred-world-clock/issues/5


Let me know how it goes,
Fede.

**Comment by Rynogertie** [comment]
Thanks @fedecalendino, that did the trick!
