### ISSUE TITLE
Feature Request: Friendly name for home.

### ISSUE THREAD

**Issue by whazlewo** [fedecalendino/alfred-world-clock#14]
I was looking through the code a bit, and was wondering if there would be an easy way to add a space in the config for setting a "Friendly name" for home.  I find when i type "now" it always takes me a second to remember that my home and the city i have as home in this tool are different.

If you have any suggestions where to start implementing this I could shape up a PR. I've been looking for a reason to get reacquainted with Alfred workflows now that all the cool config features have been added.

**Comment by fedecalendino** [comment]
Hi @whazlewo. I think I figured out a way for this. Thanks for the suggestion, its really useful!

I added it into the v2.2.0 release that you can find here: https://github.com/fedecalendino/alfred-world-clock/releases/tag/v2.2.0

Here is how it looks:

<img width="1429" alt="friendly_names" src="https://user-images.githubusercontent.com/7383708/226558135-6127377a-efa8-434c-a494-015ff6d18154.png">


Let me know if this works for you,

Fede!

**Comment by whazlewo** [comment]
This is awesome Fede!
I love how you made it more generic. I had not thought about wanting to set Friendly names for each time zone. I love it. This would even let me set the friendly name to a person (which is really how I use this, 'what time is it where Justin is...')
Thank you for doing this.

**Comment by fedecalendino** [comment]
hahah its funny that you mentioned that, because I didn't even think about using people's name for this and its genius!

I'm def stealing that idea!

Glad you are enjoying this workflow.

Cheers,
Fede!
