### ISSUE TITLE
Add ability for AM/PM to be lowercase

### ISSUE THREAD

**Issue by windblower420** [fedecalendino/alfred-world-clock#15]
Id like to have the am/pm lowercase 

i tried to change it to %P to make it lowercase in the formatters but it seems to not work.

Is this possible?

**Comment by fedecalendino** [comment]
Hi!

I like that! I added that as the default on the last version `v2.2.1`.

https://github.com/fedecalendino/alfred-world-clock/releases/tag/v2.2.1


Cheers, Fede.
