### ISSUE TITLE
TZ missing

### ISSUE THREAD

**Issue by mikedvzo** [fedecalendino/alfred-world-clock#4]
What am I missing? I found no TZ for China or India. I was expecting Beijing and Delhi as a minimum.

**Comment by fedecalendino** [comment]
Hi @mikedvzo !

The list is provided by `pytz`, a library for python to handle timezones, which sadly only provides a [standardised set of timezones](https://github.com/stub42/pytz/blob/4ebc28de7d31a80497e0bbc08042a81c8f3e591d/tz/zone.tab).

For India, you can use `🇮🇳 Asia / Kolkata` and for China you can use `🇨🇳 Asia / Shanghai`.

* https://www.zeitverschiebung.net/en/timezone/asia--kolkata
* https://www.zeitverschiebung.net/en/timezone/asia--shanghai


Let me know if this works for you.

Fede.

**Comment by mikedvzo** [comment]
Thx

--
Mike DiVincenzo
919-741-8314 (Mobile)
919-200-0638 (Home)
