### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by szfkamil** [fedecalendino/alfred-world-clock#5]
<img width="857" alt="Screenshot 2022-12-18 at 14 52 11" src="https://user-images.githubusercontent.com/82778513/208302288-7a9abaed-6c78-485d-96b4-6b1b07d3ad50.png">

**Comment by LoopKarma** [comment]
@szfkamil you can solve it by following solutions from [so](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa)

**Comment by stylophile** [comment]
> @szfkamil you can solve it by following solutions from [so](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa)

Worked for me as well. For most, simply running this will fix it:

`xcode-select --install`
