### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by epmoyer** [fedecalendino/alfred-world-clock#8]
It would be helpful to have some build instructions. 

As a very experienced python user, but a newbie to poetry and a newbie to Alfred, I wasn't able to figure out how to get the build working.

As-is, cloning the repo and running `./build.sh` fails because it is looking for a `.venv` (which doesn't exist on my machine).  Maybe there is some `poetry` magic that needs to be run first to set up the virtual environment, but I haven't used poetry before (and I usually use conda instead of venv, so I don't know my way around venv very well either). 

Thanks!

**Comment by fedecalendino** [comment]
Hi! 

To be honest I didn't though about that, but I can definitely write something up these days for people interested.

In the meantime, I can give you some pointers.

First of all, you need poetry which you can check how to install here: https://python-poetry.org/docs/#installation

Secondly, for this to work you need to indicate to poetry to create the virtual env in the project with this setting: https://python-poetry.org/docs/configuration/#virtualenvsin-project

Once you have that setted, you can install the dependencies of the workflow with this command: https://python-poetry.org/docs/cli/#install

Finally, by executing `./scripts/release.sh` you'll be able to generate a new workflow file which will be automatically imported into Alfred for you to test your changes.

ps: release files are just zip files with a different extension.

**Comment by epmoyer** [comment]
Thanks Fede! That was perfect; build working now.

Poetry (version 1.3.1) was complaining with:
```
$ poetry config virtualenvs.in-project true --local

Could not parse version constraint: latest
```
so I worked around it by changing the following in `pyproject.toml`:
```
[tool.poetry.dependencies]
python = ">=3.8,<3.11"
# EPM: Poetry complained about "latest" here, so set to current release 0.3.3 instead
# alfred-pyflow = "latest"
alfred-pyflow = "0.3.3"
pytz = "^2022.7"
``` 

My reason for tinkering was both to learn some Alfred scripting and to hack world-clock so that 1) the displayed times were in iso format and 2) both the displayed and coped times dropped the milliseconds.  I had my own little command line script that I previously used for similar functionality, but having it in Alfred now is faster to access and faster to copy (so thanks for putting this together!). 

My experience is that I want ISO times for two things: Knowing what time it is in other places (when I am trying to interpret server logs), and putting a timestamp into my notes etc.  In both cases I don't need the milliseconds, so I prefer dropping it.

If you're interested in a PR to add a checkbox to enable/disable milliseconds and a checkbox for displaying the times in iso then that's something I'd be happy to put together.

My hacked version now looks like this:
![alfred-world-clock_iso](https://user-images.githubusercontent.com/136718/210121725-73f35e5d-eeb1-43a6-97e4-d3eba52036c7.png)

And the hack looks like this:
![alfred-world-clock_code_mod](https://user-images.githubusercontent.com/136718/210121738-d867859e-d253-4080-984e-f7d000fd9148.png)

Thanks again for responding so quickly, and thanks for writing this plug-in! Cheers!

**Comment by fedecalendino** [comment]
Hi! That looks pretty good, if you want to do a PR with a checkbox for either what I had or that ISO format that would be great!

if you prefer instead of a checkbox you could add a dropdown with possible formatting strings. By default would be the one that I had, optionally the one that you wanted and a third one if you want.

**Comment by fedecalendino** [comment]
Added a `SETUP.md` file for this!

https://github.com/fedecalendino/alfred-world-clock/blob/main/SETUP.md

Fede.
